blank_issues_enabled: false
contact_links:
  - name: ğŸ’ Preciso de ajuda!
    url: https://loritta.website/br/support
    about: Visite o nosso servidor de suporte para conseguir ajuda!
  - name: ğŸ—ï¸ Quero comprar vips e modos!
    url: https://youtu.be/dQw4w9WgXcQ
    about: Visite o nosso website para obter os cosmÃ©ticos do nosso servidor.
